### ISSUE TITLE
Redis: READONLY You can't write against a read only slave.

### ISSUE THREAD

**Issue by BezVezeE** [kubernetes/examples#165]
Hi, can someone help me with a problem on the redis cluster, 

for example i use google cloud and i have created the redis cluster with the redis sentinel svc, also deleted the master pod an recreated again by it self, (as told in the example) 

but can someone have any idea how to use this cluster,

i created a internal loadbalancer svc 

```
apiVersion: v1
kind: Service
metadata:
  name: redis-loadbalancer
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    name: redis
spec:
  type: LoadBalancer
  loadBalancerIP:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    name: redis
```

and the good thing is i can connect to the cluster  
but when i try to insert some data it gives me an error

```
redis-cli -h 10.128.0.11 -p 6379
10.128.0.11:6379> set test test
(error) READONLY You can't write against a read only slave.
10.128.0.11:6379> 
```
