### ISSUE TITLE
NFS example using hard coded IP rather than service

### ISSUE THREAD

**Issue by day1118** [kubernetes/examples#237]
Why does the NFS example use a hard coded IP rather than a service. Can you please add a note of why this is the case?

Thanks

**Comment by ekhaydarov** [comment]
yeah theres a few hiccups when trying to move away from static ips to service which is undocumented

**Comment by walterdolce** [comment]
/remove-lifecycle stale

Is anyone able to document the undocumented stuff please?

**Comment by abeckDev** [comment]
/remove-lifecycle stale

I am also running into this problem and would really appreciate if anyone could document why we can't use Kubernetes services to connect to the NFS server.

@fejta are you able to help here?

**Comment by recipedude** [comment]
/remove-lifecycle stale

If we are forced to define the NFS based PV using an IP address rather than service DNS does anyone have a reference to docs on how to fix the IP address of a pod?  

Of course, doing so is extremely unpleasant. 

https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
```The Pods’ ordinals, hostnames, SRV records, and A record names have not changed, but the IP addresses associated with the Pods may have changed. In the cluster used for this tutorial, they have. This is why it is important not to configure other applications to connect to Pods in a StatefulSet by IP address.```

**Comment by recipedude** [comment]
Hey @abeckDev, indeed.  

Yet the NFS example https://github.com/kubernetes/examples/blob/master/staging/volumes/nfs/nfs-pv.yaml uses static IP address.  Believe I am not the only one that has tried to use the service DNS name in the NFS based PV, only to find that it fails with unresolvable name service.  However, it does work when using a static IP address manually entered.  Yuck. 

I do recall seeing an example of an IP being set statically in a k8s resource and immediately thought something along the lines of "oh man, that's just wrong", been hunting for where I saw that. 

Found it, @kelseyhightower appears to be advocating setting a service to a predefined static IP on a service resource here: https://github.com/kelseyhightower/kubernetes-redis-cluster/blob/master/services/redis-2.yaml
in the https://github.com/kelseyhightower/kubernetes-redis-cluster project that may have been used for a Redis on Kubernetes talk he did.

Maybe by tagging him here, this issue might get some love? :)

**Comment by abeckDev** [comment]
That's it! I ran in the exact same issue and thought that that cant be the way. After looking at GitHub I was happy that there was already an issue and a confirmation from the K8s team but unfortunenatly it is kind of abandoned now. 

But I think using the NFS example to provide a powerful IO and low latency share in the cluster is a realy cool feature so it would be great if that Issue get resolved. Because although its possible, assigning static IPs or copying the assigned IP from K8s isn't a real solution in my opinion.

**Comment by recipedude** [comment]
@abeckDev Copying the assigned IP as shown in the "official" example feels wrong on so many levels. Am guessing that any deployment using that any such configuration will inevitably break. 

For the time being it appears that the lesser evil is to, even have trouble writing this, assign the containerized NFS server service resource a static IP as thus:

```
apiVersion: v1
kind: Service
metadata:
  name: nfs-shared
  namespace: shared
  labels:
    app: nfs-shared
spec:
  ports:
  - port: 2049
    name: nfs-shared
  selector:
    app: nfs-shared
  clusterIP: "10.96.254.254"
```

And the PV would appear something like:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-shared
  namespace: shared
  labels:
    bucket: shared
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes: 
    - ReadWriteMany
  nfs:
#    server: nfs-shared-0.nfs-shared.shared.svc.cluster.local 
    server: 10.96.254.254
    path: /
```

Yuck; but at least it hopefully will not break when the NFS server pod is killed, restarted or moves from node to node.   No idea how one even goes about choosing an IP address for this.  It's gross but seems to work so far...
