### ISSUE TITLE
fsGroup securityContext does not apply to nfs mount

### ISSUE THREAD

**Issue by kmarokas** [kubernetes/examples#260]
The example https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs works fine if the container using nfs mount is running as root user. If I use securityContext to run not as root user then I have no write access to the mounted volume.

How to reproduce:
here is the nfs-busybox-rc.yaml with securityContext:
```
# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-busybox
spec:
  replicas: 2
  selector:
    name: nfs-busybox
  template:
    metadata:
      labels:
        name: nfs-busybox
    spec:
      securityContext:
        runAsUser: 10000
        fsGroup: 10000
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/index.html; hostname >> /mnt/index.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        securityContext:
          runAsUser: 10000
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/mnt"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
```

Actual result:
```
kubectl exec nfs-busybox-2w9bp -t -- id
uid=10000 gid=0(root) groups=10000

kubectl exec nfs-busybox-2w9bp -t -- ls -l /
total 48
<..>
drwxr-xr-x    3 root     root          4096 Aug  2 12:27 mnt
```
Expected result:
the group ownership of /mnt folder should be user 10000

The mount  options in nfs pv are not allowed except rw
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.23.137.115
    path: "/"
  mountOptions:
#    - rw // is allowed
#    - root_squash // error during pod scheduling: mount.nfs: an incorrect mount option was specified
#    - all_squash // error during pod scheduling: mount.nfs: an incorrect mount option was specified
#    - anonuid=10000 // error during pod scheduling: mount.nfs: an incorrect mount option was specified
#    - anongid=10000 // error during pod scheduling: mount.nfs: an incorrect mount option was specified
```

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.3-rancher1", GitCommit:"f6320ca7027d8244abb6216fbdb73a2b3eb2f4f9", GitTreeState:"clean", BuildDate:"2018-05-29T22:28:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jefflaplante** [comment]
Why did this get closed with no resolution? I have this same issue. If there is a better solution than an init container please someone fill me in.

**Comment by geerlingguy** [comment]
Yeah... I'm having the same issue with NFS too. `securityContext.fsGroup` seems to have no affect on NFS volume mounts, so you kinda have to use the initContainer approach :(

**Comment by mlensment** [comment]
Why's this issue closed? I'm having the same problem.

**Comment by pankajcheema12** [comment]
same issue able to write but not able to read from nfs mounted volume . kubernetes shows success in mounting process but no luck .

**Comment by varun-da** [comment]
thanks @kmarokas!

**Comment by leopoldodonnell** [comment]
Would love for this to be addressed! In the mean time here's how we're dealing with it...

In this example there are two pods that are mounting an AWS EFS volume via nfs. To enable a non-root user, we make the mount point accessible via an initContainer.

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-efs-1
  labels:
    name: alpine
spec:
  volumes:
  - name: nfs-test
    nfs:
      server: fs-xxxxxxxx.efs.us-east-1.amazonaws.com
      path: /
  securityContext:
    fsGroup: 100
    runAsGroup: 100
    runAsUser: 405
  initContainers:
    - name: nfs-fixer
      image: alpine
      securityContext:
        runAsUser: 0
      volumeMounts:
      - name: nfs-test
        mountPath: /nfs
      command:
      - sh
      - -c
      - (chmod 0775 /nfs; chgrp 100 /nfs)
  containers:
  - name: alpine
    image: alpine
    volumeMounts:
      - name: nfs-test
        mountPath: /nfs
    command:
      - tail
      - -f
      - /dev/null
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-efs-2
  labels:
    name: alpine
spec:
  volumes:
  - name: nfs-test
    nfs:
      server: fs-xxxxxxxx.efs.us-east-1.amazonaws.com
      path: /
  securityContext:
    supplementalGroups:
      - 100
    fsGroup: 100
    # runAsGroup: 100
    runAsUser: 405
  initContainers:
    - name: nfs-fixer
      image: alpine
      securityContext:
        runAsUser: 0
      volumeMounts:
      - name: nfs-test
        mountPath: /nfs
      command:
      - sh
      - -c
      - (chmod 0775 /nfs; chgrp 100 /nfs)
  containers:
  - name: alpine
    image: alpine
    volumeMounts:
      - name: nfs-test
        mountPath: /nfs
    command:
      - tail
      - -f
      - /dev/null
```

**Comment by spawnia** [comment]
The same seems to be true for cifs mounts created through a custom volume driver: https://github.com/juliohm1978/kubernetes-cifs-volumedriver/issues/8

**Comment by slayer01** [comment]
no solution since around 1 1/2 years? cant believe it.

**Comment by spawnia** [comment]
/remove-lifecycle rotten

Maybe this issue needs to be taken to another repository. Is https://github.com/kubernetes-incubator/external-storage the right place for it?

**Comment by raajavel** [comment]
is there any solution for it other than initContainers ?

**Comment by spawnia** [comment]
> fsGroupChangePolicy: "Always"

The docs are not totally clear about this, but I understand that this is already the default behaviour.

> By default, Kubernetes recursively changes ownership and permissions for the contents of each volume to match the fsGroup specified in a Pod's securityContext when that volume is mounted.

The section also indicates that not every volume type necessarily supports changing permissions:

> This field only applies to volume types that support fsGroup controlled ownership and permissions.

**Comment by ravikanth39** [comment]
+1

**Comment by eakurdyukov** [comment]
The same issue for AWS EBS gp2 volumes

**Comment by tetsun** [comment]
+1

**Comment by darose** [comment]
I just ran into this issue today as well.  Is there any workaround yet besides using an initContainer?

**Comment by bynare** [comment]
+1 - facing this issue too!

**Comment by vishwa-vyom** [comment]
+1 - facing this issue

**Comment by abdennour** [comment]
fsGroup is used to control access to BLOCK storage (.eg: iSCSI, Ceph RBD, .. ).. and not for File Storage like NFS. 
Note that

**Comment by droctothorpe** [comment]
Has anyone been able to do this without an init container? Really hoping to avoid that if possible.

**Comment by vijay-at-work** [comment]
I would rather avoid init containers, in fact I don't like any kind of scripts in the k8s manifests!
So If you don't want to use init container, you can do something like this -

_e.g. for nfs volumes_ (This assumes you have control over nfs server)
On the nfs server have something like this in `/srv/exportfs`
`/srv/vol1       *(rw,sync,all_squash,insecure,no_subtree_check,anonuid=2000,anongid=3000)`
 Also change perms on /srv/vol1 to match above
`chmod -R 2000:3000 /srv/vol1`

In the pod use security context to match above -
```
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 3000
    fsGroupChangePolicy: Always
```
I like this better than allowing to run as root in init containers. (`PodSecurityPolicy` may prevent it as well)
Also this is a better way for dishing out volumes with well known uid:gid that anyone can predictably use.

_You can also use the same technique with hostPath based volumes._

Alternatively if you want to use commercial persistent volumes like _aws/gcp/portworxVolume_ etc, it will depend on whether they support `fsGroup`.
