### ISSUE TITLE
Redis sentinel example

### ISSUE THREAD

**Issue by AlexProfi** [kubernetes/examples#297]
Hi
I try to run redis sentinel by this tutor
https://github.com/kubernetes/examples/tree/master/staging/storage/redis

and get that there is no master after I delete pod redis-master

```
redis-9kmr9                            1/1       Running   1          4m
redis-p2thm                            1/1       Running   2          4m
redis-sentinel-8ghzb                   1/1       Running   0          4m
redis-sentinel-lwhhs                   1/1       Running   0          4m
redis-sentinel-nwrlc                   1/1       Running   0          4m
redis-xq2td                            1/1       Running   0          2m
reloader-b4c8c8954-dc8l5               1/1       Running   1          1d
rsyslog-example-app-86d86589bc-mlgp7   1/1       Running   5          3d
rsyslog-server-86f8bfcf9-d2x72         1/1       Running   5          3d
web-0                                  1/1       Running   0          9h
web-1                                  1/1       Running   1          9h
root@hb-master01:/home/master01/configs/host/k8s# kubectl exec -it redis-xq2td  -- redis-cli info|grep ^role
role:slave
```
I use this configmaps

```
apiVersion: v1
kind: ConfigMap
data:
  redis-config: |
   
    daemonize no

   
    pidfile /var/run/redis.pid

 
    port 6379

  
    tcp-backlog 65536

 

    bind 0.0.0.0

 
    timeout 0

    # TCP keepalive.
 
    tcp-keepalive 60

  
    loglevel notice

   
    databases 16
    save 900 1
    save 300 10
    save 60 10000 
    stop-writes-on-bgsave-error yes

    rdbcompression yes

    rdbchecksum yes

    # The filename where to dump the DB
    dbfilename dump.rdb

  
    dir "./"

   
    slaveof %master-ip% %master-port%

  
    slave-serve-stale-data yes

   
    slave-read-only yes

    repl-diskless-sync no

   
    repl-diskless-sync-delay 5

  
    # repl-ping-slave-period 10

  
    repl-disable-tcp-nodelay no

  
    slave-priority 100

 
    # MAXMEMORY POLICY: how Redis will select what to remove when maxmemory
    # is reached. You can select among five behaviors:
  
    appendonly yes

    # The name of the append only file (default: "appendonly.aof")

    appendfilename "appendonly.aof"


    no-appendfsync-on-rewrite no

  

    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    aof-load-truncated yes

    ################################ LUA SCRIPTING  ###############################


    lua-time-limit 5000

 
    slowlog-log-slower-than 10000

    # There is no limit to this length. Just be aware that it will consume memory.
    # You can reclaim memory used by the slow log with SLOWLOG RESET.
    slowlog-max-len 128

    latency-monitor-threshold 0

    notify-keyspace-events ""

    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-entries 512
    list-max-ziplist-value 64
    set-max-intset-entries 512

    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10

    # When a child rewrites the AOF file, if the following option is enabled
    # the file will be fsync-ed every 32 MB of data generated. This is useful
    # in order to commit the file to the disk more incrementally and avoid
    # big latency spikes.
    aof-rewrite-incremental-fsync yes
    logfile /data/log.log
    maxmemory-policy allkeys-lru

metadata:
   name: redis-slave-conf
   namespace: default


apiVersion: v1
kind: ConfigMap
data:
  redis-config: |
    daemonize no

    pidfile /var/run/redis.pid
    port 6379
    tcp-backlog 65536

    bind 0.0.0.0
    timeout 0
    tcp-keepalive 60
    loglevel notice
    databases 16

    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes

    # The filename where to dump the DB
    dbfilename dump.rdb
    dir /redis-master-data

    slave-serve-stale-data yes

    slave-read-only yes
    repl-diskless-sync no

    repl-diskless-sync-delay 5
    # If you select "yes" Redis will use a smaller number of TCP packets and
    repl-disable-tcp-nodelay no
    slave-priority 100
    appendonly yes

    # The name of the append only file (default: "appendonly.aof")

    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no

    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    aof-load-truncated yes

    lua-time-limit 5000

    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 0

    notify-keyspace-events ""

    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-entries 512
    list-max-ziplist-value 64
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    activerehashing yes

    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    aof-rewrite-incremental-fsync yes
    logfile /data/log.log
    maxmemory-policy allkeys-lru

metadata:
   name: redis-master-conf
   namespace: default
```

And this yaml files for describe redis configs
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: redis
    redis-sentinel: "true"
    role: master
  name: redis-master
spec:
  volumes:
    - name: master-config
      configMap:
        name: redis-master-conf
        items:
        - key: redis-config
          path: redis.conf
    - name: slave-config
      configMap:
        name: redis-slave-conf
        items:
        - key: redis-config
          path: redis.conf
    - name: data
      emptyDir: {}
  containers:
    - name: master
      image: k8s.gcr.io/redis:v1
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
#      resources:
#        limits:
#          cpu: "90"
      volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - name: master-config
          mountPath: /redis-master
        - name: slave-config
          mountPath: /redis-slave
    - name: sentinel
      image: k8s.gcr.io/redis:v1
      env:
        - name: SENTINEL
          value: "true"
      ports:
        - containerPort: 26379


apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
        role: master
    spec:
      containers:
      - name: redis
        image: k8s.gcr.io/redis:v1
        ports:
        - containerPort: 6379
#        resources:
#          limits:
#            cpu: "90"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - name: master-config
          mountPath: /redis-master
        - name: slave-config
          mountPath: /redis-slave
      volumes:
        - name: data
        - name: master-config
          configMap:
            name: redis-master-conf
            items:
            - key: redis-config
              path: redis.conf
        - name: slave-config
          configMap:
            name: redis-slave-conf
            items:
            - key: redis-config
              path: redis.conf

```

How to fix it?
And how connect to this master to set data ? I need permanent name for it for programming access by host name or name of service
