### ISSUE TITLE
Missing service type on guestbook-all-in-one.yaml

### ISSUE THREAD

**Issue by cyberpau** [kubernetes/examples#368]
https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml

Here is a snippet of the current configuration of Front-End Service:

```
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
```

As you can notice, the type `LoadBalancer` is commented out, therefore the default `ClusterIP` type is selected instead of `NodePort` as per the tutorial (https://kubernetes.io/docs/tutorials/stateless-application/guestbook/#set-up-and-expose-the-guestbook-frontend)

Because of this issue, if you run:
`minikube service frontend --url`

It will show this error/warning:
`😿  service default/frontend has no node port`
