### ISSUE TITLE
pod yaml with condition

### ISSUE THREAD

**Issue by sonuchauhan1597** [kubernetes/examples#399]
Hi, 

I have created a pod YAML.
Below is the snippet.
```
- name: log-storage
    persistentVolumeClaim:
      claimName: log-pvc
    when: pv_server != "" and pv_path != ""
```
but this condition is not effective. 

 ```
 log-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:   log-pvc
    ReadOnly:   false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  10s   default-scheduler  persistentvolumeclaim "log-pvc" not found
```

Is there any way to handle conditions in pod YAML instead of creating a separate YAML? 

Thank you.
