### ISSUE TITLE
GlusterFS Endpoints cross-namespace

### ISSUE THREAD

**Issue by Y0ngg4n** [kubernetes/examples#436]
How can i reference a glusterfs endpoint that is created in the default namespace in my PersistentVolume for example?
When i use this PV 
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nextcloud-html-pv
  namespace: nextcloud
  labels:
    app: nextcloud
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  glusterfs:
    endpoints: glusterfs-cluster.default
    path: /k-repl/storage/nextcloud/html
```
i get following error:
`MountVolume.NewMounter initialization failed for volume "nextcloud-html-pv" : endpoints "glusterfs-cluster.default" not found`
I have also tried `glusterfs-cluster.default.svc.cluster.local` but did not work.
