### ISSUE TITLE
Proposing fix for the inaccessible console for Minio on browser.

### ISSUE THREAD

**Issue by LilMonk** [kubernetes/examples#464]
I have found a fix for this issue. It was also raised over here #424. So basically we need to add some more arguments in the deployment container spec. Can I make a PR for the same?

**Comment by LilMonk** [comment]
Also added the PersistentVolume:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name uniquely identifies the PVC. Will be used in deployment below.
  name: minio-pv-claim
  labels:
    app: minio-storage-claim
spec:
  # Read more about access modes here: http://kubernetes.io/docs/user-guide/persistent-volumes/#access-modes
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    # This is the request for storage. Should be available in the cluster.
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-storage
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mydata/minio
    type: DirectoryOrCreate
```
