### ISSUE TITLE
guestbook: consider splitting service file into two

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/examples#50]
Currently we're telling people:

```yaml
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ...
```

Instead of this we should have 2 files that are ready to be deployed, configured with NodePort and LoadBalancer respectively.

This way we can say "if you're on minikube, deploy `frontend-service.yaml`, if you're on a cloud provider, deploy `frontend-service-external.yaml`.

cc: @cody-clark
